accent_color: '#2d72d9'
lang: en-US
title: Name Every Number
description: 'A math blog'
baseurl: ''
url: 'https://nameeverynumber-01e4a.netlify.com/'
permalink: '/:title'
favicon: images/favicon.png
disqus: justgoodthemes
navigation:
  - text: Home
    url: /
  - text: About
    url: /about/
  - text: Contact
    url: /style-guide/
  - text: Studygram
    url: /tags/
  - text: Studyblr
    url: 'https://nameeverynumber.tumblr.com'
  - text: YoutTube
    url: 'https://github.com/JustGoodThemes/Scriptor-Jekyll-Theme'
footer:
  content: >-
    &copy; Scriptor all rights reserved. Theme by
    [JustGoodThemes](https://www.justgoodthemes.com).
  has_social: true
plugins:
  - jekyll-paginate
paginate: 3
paginate_path: '/page:num/'
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed
