accent_color: '#2d72d9'
lang: en-US
title: Name Every Number
description: A math blog.
baseurl: 'https://nameeverynumber-01e4a.netlify.com/'
url: 'https://nameeverynumber-01e4a.netlify.com/'
permalink: '/:title'
favicon: images/favicon.png
disqus: justgoodthemes
navigation:
  - text: Home
    url: /
  - text: About
    url: /about/
  - text: Contact
    url: /contact/
  - text: Studygram
    url: 'https://www.instagram.com/nameeverynumber/'
  - text: Studyblr
    url: 'https://nameeverynumber.tumblr.com'
  - text: YouTube
    url: 'https://github.com/JustGoodThemes/Scriptor-Jekyll-Theme'
footer:
  content: >-
    &copy; Vanessa Sun
  has_social: true
plugins:
  - jekyll-paginate
paginate: 3
paginate_path: '/page:num/'
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed
